### ISSUE TITLE
Learn spellings / Add words to dictionary 

### ISSUE THREAD

**Issue by thedataking** [atom/spell-check#10]
It seems I can't teach the spell-check new words. This is a crucial feature, please add. If this feature exists already, it needs to be made discoverable, e.g. by right clicking the word, from the command palette, etc.

Thanks!

**Comment by hermanbergwerf** [comment]
I don't believe this features has been added yet. I've been spending hours trying to figure out a way to get rid of those extremely annoying red dashes below quite common words like "wireframes", "frontend", "backend", etc. I found that `spell-check` relies on `node-spellchecker` which ships dictionaries for hunspell itself (leaving any system dictionaries, I think) The only way I found to add words is to edit `/usr/share/atom/resources/app/node_modules/spell-check/node_modules/spellchecker/vendor/hunspell_dictionaries/en_US.dic` Of course I do not recommend this method to anybody. I hope a more user friendly way of adding words to the spell checker dictionary will be implemented soon!

**Comment by CrouseMatthew** [comment]
+1

**Comment by mrz1836** [comment]
+1

**Comment by Wikunia** [comment]
+1
Project level or globally and maybe export/import the words this would be useful for teams.

**Comment by CrouseMatthew** [comment]
+1

**Comment by willwoodlief** [comment]
+1

**Comment by laughedelic** [comment]
+1

**Comment by Meligy** [comment]
+1

Ideally globally, with an option in context menu or `CMD` + `SHIFT` + `P`.

The effect will be nice saved to a configuration file (whatever Atom uses for user package config, not familiar with config in Atom still sorry).

Obviously, it's open source, so thanks a million to everyone working on this whom I benefit from their work without asking for anything.

**Comment by OmarIthawi** [comment]
+1

**Comment by peter1000** [comment]
+1

**Comment by mnquintana** [comment]
Thanks for the feedback everyone! However, all these +1s and :+1:s are just adding noise, so to minimize that I'm going to lock this issue for now – we may unlock it once someone starts working on this enhancement to get further feedback.

**Comment by 50Wliu** [comment]
At the current pace of development, this feature will be available starting in Atom 1.11.0.
