### ISSUE TITLE
Docs pretend issue #11 doesn't exist

### ISSUE THREAD

**Issue by OJFord** [atom/spell-check#101]
The [documentation describes changing spell-check language](https://atom.io/docs/v1.3.2/using-atom-writing-in-atom#spell-checking), but we know this isn't possible/doesn't work, as discussed in #11.

Furthermore, that discussion is locked until "someone starts working on [it]", and has been since August 2015. This being a pretty long-lived (and with no end in sight) bug/missing feature, it seems beyond misleading to describe "how to" change spell-check language in docs.

Obviously everyone's preferred solution is to fix #11, but until that's done, this description should be removed from the guide.

**Comment by lee-dohm** [comment]
This issue was moved to atom/docs#153
