### ISSUE TITLE
Performance issues when editing Latex on Mac

### ISSUE THREAD

**Issue by kmisiunas** [atom/spell-check#111]
I am using Atom 1.4.3 for latex editing. I noticed that for files larger than ~10KB the spell checking becomes very slow. Also the CPU usage increases to unacceptable levels:

<img width="418" alt="screen shot 2016-02-08 at 18 09 54" src="https://cloud.githubusercontent.com/assets/4820843/12905846/8f8e4520-ce8f-11e5-8a02-623744771695.png">

This happened on MAC OS X 10.11.3. 

Any ideas why?

**Comment by 50Wliu** [comment]
Hi @kmisiunas, sorry for the trouble.  Spell-checking performance was recently improved though, and you should start seeing noticeable improvements starting in Atom 1.6.0.

**Comment by kmisiunas** [comment]
ok. I am looking forwards to it!
