### ISSUE TITLE
Latex command (\emph) and words in .gitignore recently labeled as mis-spelled

### ISSUE THREAD

**Issue by pydolan** [atom/spell-check#117]
I recently updated Atom and several packages, and since then, `\emph` in my .tex files and various words in my .gitignore files (e.g., "venv", "pyc") are being labeled as a mis-spelled words.

My spell-check grammar setting is as follows: `text.tex.latex, source.asciidoc, source.gfm, text.git-commit, text.plain, text.plain.null-grammar`

I'm running atom 1.5.3, spell-check 0.65.0, language-latex 0.6.1, latex 0.29.0 (on OS X)

My colleague has atom 1.4.1, spell-check 0.63.0, language-latex 0.6.1, latex 0.28.2 (on OS X), and neither the .gitignore nor the `\emph` are having these spelling issues highlighted.

**Comment by X-G** [comment]
me too. Not only `\emph`, lots of command like `\eqref`, `\bm`, `\frac` are labeled as mis-spelled.

**Comment by lee-dohm** [comment]
Can either of you supply a `.tex` document that reproduces the problem?

**Comment by pydolan** [comment]
Here's a screenshot of the various commands/tags being marked with spelling problems: 
<img width="741" alt="screen shot 2016-03-08 at 9 13 55 am" src="https://cloud.githubusercontent.com/assets/467780/13603855/2c584bfa-e50e-11e5-8592-ec8fdaa897d7.png">

Here's the actual tex file (rename to paper.tex and install `language-latex` for color-coding):
[paper.tex.txt](https://github.com/atom/spell-check/files/163290/paper.tex.txt).

**Comment by pydolan** [comment]
Here's an example of a .gitignore file having the spelling mistakes (I'm pretty sure they didn't show in the past, but I could be misremembering):

<img width="645" alt="screen shot 2016-03-08 at 9 41 08 am" src="https://cloud.githubusercontent.com/assets/467780/13604702/fe8ac12c-e511-11e5-8c92-86f84796d801.png">

**Comment by lee-dohm** [comment]
If you could post these in a Gist, that would be ideal. That way we don't have to retype everything :grinning:

**Comment by pydolan** [comment]
.gitignore gist: https://gist.github.com/pydolan/766bbb00877f71379be6

paper.tex gist: https://gist.github.com/pydolan/79d2a729d405fcc264ec

**Comment by lee-dohm** [comment]
Thanks a bunch!

**Comment by lvgeng** [comment]
Yes... I suffered from the same problem.
I guess the .tex files are just regarded as normal plain text while we use text.tex.latex.
Hoping there will be a result soon.

**Comment by ivlis** [comment]
Is it possible to set grammars **not to be** checked? Latex commands have the grammar `meta.function.*.latex` and the environments `meta.function.environment.general.latex`.  However, we should spellcheck arguments for **some** of latex functions, like `\caption{here we should check}` or `\emph{and here}` but we should not check here `\usepackage{package_name_should_not_be_checked}`. I don't know how to deal with this, but at least  not highlighting commands will be very good.

**Comment by deltaflyer** [comment]
I just upgraded to Atom 1.6.0 from Atom 1.0.11. Since the update, I have the problem with Latex commands, too. Latex commands and options in { } and [ ] are also spell checked, although this is not required. So I downgraded to Atom 1.0.11 and everything works fine again. I will try the upgrade in a few weeks in the hope that things are working then.

**Comment by danielchatfield** [comment]
@lee-dohm Is the `needs-reproduction` tag accurate? I haven't experienced any difficulty reproducing this.

**Comment by lee-dohm** [comment]
@danielchatfield `needs-reproduction` is also a flag for our QA folks to validate this. But you're right, in this case it is a little out of date.

**Comment by pydolan** [comment]
@lee-dohm -- I hate to continue debate of label semantics, but since this issue was not a problem at one point, I assume some change to this package or Atom introduced the bug, thus a "Bug" or "Regression" label might be more appropriate. (Of course, only if those actually get more attention.) :)

If you or anyone else has idea of where a fix may take place, please advice.  I might eventually get motivated enough to try helping with a fix, and having some idea of where to start would be helpful.
