### ISSUE TITLE
Enable spell check fix on single right click.

### ISSUE THREAD

**Issue by sylvesterjakubowski** [atom/spell-check#119]
Nearly every text editor presents spell check options when you right click to fix a spelling error.

Atom requires right click and then  click "Correct Spelling" to present spelling options.

These options should be in the right click menu when you right click a misspelled word.

**Comment by lee-dohm** [comment]
This is a duplicate of https://github.com/atom/spell-check/issues/54. Please subscribe there for updates.

Thanks for reporting!
