### ISSUE TITLE
Spell Check Not Working

### ISSUE THREAD

**Issue by rr1000** [atom/spell-check#12]
This package doesn't seem to be working at all.

OSX: 10.9.1
Version: 0.67.0

![screen shot 2014-03-05 at 7 05 07 pm](https://f.cloud.github.com/assets/1596785/2340428/0206d9a8-a4c3-11e3-8e48-ff551d585a8b.png)

**Comment by dannymichel** [comment]
I dont have a spell.check.grammars array.

**Comment by MClatter** [comment]
Strange thing. When I start Atom from Git Bash, spell check doesn't work (it underlines everything) but any other way starting Atom is fine.
