### ISSUE TITLE
Keybinding for toggling spell check of document

### ISSUE THREAD

**Issue by JohnLukeBentley** [atom/spell-check#124]
This is request to add a keybinding for toggling the spell check of a document.

At the moment a keybinding exists for displaying corrected spelling options when the cursor is over a misspelled word ...
'.platform-win32 atom-text-editor':
  'ctrl-:': 'spell-check:correct-misspelling'

... however I'm suggesting an additional keybinding that actuates the Atom > Packages > Spell Check > Toggle command (which toggles the display of red underlined misspelled words in a document).

**Comment by lee-dohm** [comment]
In the meantime, you can always add your own key binding for this. See the [Keybindings section in the Flight Manual](http://flight-manual.atom.io/using-atom/sections/basic-customization/) for details.

**Comment by 50Wliu** [comment]
This was added in #33 and will be available in Atom 1.7.0!

**Comment by JohnLukeBentley** [comment]
@lee-dohm the problem was the lack of key hook (whatever this is called in Atom) in order set a custom keybinding. But it looks like this has been fixed, with thanks @50Wliu.

**Comment by nolanbconaway** [comment]
For reference, here's an example toggle binding:

```cson
'.platform-darwin atom-text-editor':
  'alt-cmd-c': 'spell-check:toggle'
```
