### ISSUE TITLE
Meta: Unlock Issue #10 for discussion

### ISSUE THREAD

**Issue by lazytype** [atom/spell-check#128]
+1 spam shouldn't be a concern anymore now that Github supports reactions. Would there be any harm in unlocking the comments?

**Comment by 50Wliu** [comment]
Unfortunately, we've found that many people ignore the reactions and continue to simply add "+1" comments, so for the most part we've been unwilling to unlock any issues that have attracted such comments.  I'll bring it up with the team though!

**Comment by lee-dohm** [comment]
@lazytype What sort of discussion would you like to have? It is something that we acknowledge should be done whether by us or a member of the community. I honestly doubt anyone is going to say that it shouldn't be done. Discussions on how to make it happen can occur in PRs that begin implementing it.

**Comment by lazytype** [comment]
I guess one thing I noticed in the original thread is that there didn't seem to be much consensus on what the current technical limitations were or what the desirable approach would be. There was some speculation by other users, but it would feel more definitive with some affirmation/input from the primary contributors.

**Comment by lee-dohm** [comment]
It was unlocked for over a year without much traffic other than +1s. I doubt that it is going to start generating meaningful discussion now if unlocked.

I'm working on some tools for maintainers to keep up with the right things without getting spammed by inconsequential stuff. When those are in place, I'll be unlocking all but the most egregious Issues. I don't have an ETA for it at this point as it is still in the early stages.

I know that's not the answer you're looking for but I hope it helps :grinning:

**Comment by rm-code** [comment]
Would be nice if we could have reactions on closed threads too.
