### ISSUE TITLE
Can't get spell check to do anything

### ISSUE THREAD

**Issue by lotka** [atom/spell-check#142]
I have tired adding the correct cursor scope, tried using a simple .txt file and have had no luck getting those wavy red lines. I'm running on:

```
Ubuntu 15.10
linux kernel: 4.2.0-23-generic x86_64
Atom 1.8.0
```

I did manage to get it to work on another machine running Ubuntu 14 and Atom 1.6.0, even for latex files.

**Comment by Nikoleta-v3** [comment]
same here and  I am running on Ubuntu 16.04

**Comment by SamuelMarks** [comment]
Same here on Ubuntu 16.04 x64 with Atom 1.8.0 and spell-check 0.67.1

**Comment by konstantinmagg** [comment]
Hi there,
same here with Atom 1.7.3, spell-check 0.67.0 on Ubuntu 16.04 x64. But I can remember, I had this package nicely working on my old Win 7 machine some weeks ago.

Did anyone figure out, what the problem is?

**Comment by MrPrimate** [comment]
Same here Ubuntu Gnome 16.04, Atom 1.7.2

**Comment by denniss17** [comment]
Could be related: https://github.com/atom/spell-check/issues/105

**Comment by Nikoleta-v3** [comment]
@denniss17  good tip for Latex but unfortunately it is not the same issue. Because it does not seem to work even for plain tex files.

**Comment by denniss17** [comment]
@Nikoleta-v3 It could be related. I believe it didn't work for me at all, but I only experienced this issue while editing LaTeX. Anyway it seems to be fixed for me know, and as stated in the other issue I believe it has something to do with the EN-US dictionary not being installed on the OS.

**Comment by genvoa** [comment]
Same on WIndows 10, atom 1.8. Seems like spell check does nothing at all.

**Comment by mcrotty** [comment]
On Ubuntu 14.04, atom 1.8. Same issue.

However a workaround is to set the LANG var back to US English. (see https://github.com/atom/spell-check/pull/114) e.g.

export LANG=en_US.UTF-8
d43$ atom doc.asciidoc

**Comment by 50Wliu** [comment]
Closing in favor of #129 - feel free to subscribe there for updates.
