### ISSUE TITLE
Possible solution for mulit lingual spellchecking

### ISSUE THREAD

**Issue by git001** [atom/spell-check#143]
Due to the fact that issue #11 is not editable I open this issue for a possible solution.

I was able to add de_AT to atom spellchecker with the following steps.
I assume this works on most linux.
- install hunspell and your language
- execute `hunspell -D` to get the location of the spell files
- copy the files into the atomic dir

```
 cp /usr/share/myspell/de_AT.* /usr/share/atom/resources/app.asar.unpacked/node_modules/spell-check/node_modules/spellchecker/vendor/hunspell_dictionaries/
```
- start atom with the lang variable set

```
LANG=de_AT /usr/bin/atom -f
```

This solution works only with one language per atom instance.

**Comment by ludus-leonis** [comment]
Awesome! Finally at least a workaround!
Is it possible to copy the language files to the `~/.atom` directory instead, so I do not have to mess around in the system directories? I tried creating the whole `resources/...` in there, but this seems not to work.

**Comment by git001** [comment]
I haven't seen an option to set the path.

https://github.com/atom/node-spellchecker/blob/master/lib/spellchecker.js#L17
https://github.com/atom/node-spellchecker/blob/master/lib/spellchecker.js#L61

**Comment by dmoonfire** [comment]
Issue https://github.com/atom/spell-check/pull/120, which was recently merged for around 1.11, attempts to fix that by allowing both a search path for non-Windows machines and also to specify the locales via settings.

You can test it using `spell-check-test` which is my development package. You have to disable `spell-check` to use it.

**Comment by stesachse** [comment]
@dmoonfire is there a way to report issues with `spell-check-test`. i have installed it and it works for me. with the original package a got nothing. no error, no markers, no correction. but now i got a encoding problem with german "umlauts"

**Comment by dmoonfire** [comment]
@stesachse Sure, just report the issue either here (it's going to be in v1.12 anyways) or over at https://github.com/dmoonfire/spell-check.

**Comment by stesachse** [comment]
@dmoonfire issues are disabled on https://github.com/dmoonfire/spell-check

here we go: #161

**Comment by dmoonfire** [comment]
I believe this has been resolved with various changes to `spell-check` in the last few years, I'm going to close it. Feel free to open if you don't agree.
