### ISSUE TITLE
Windows 7: Cannot find dictionary for en_US

### ISSUE THREAD

**Issue by cynicated** [atom/spell-check#162]
With the spell-check plugin enabled, and even toggled multiple times, I cannot get any form of spell checking. 

Checking through the console logs, I found the following line:
`spell-check:en-us Can't load en_US: Cannot find dictionary for en_US.`

I am running Windows 7 Enterprise, with Atom 1.11.1.

I've verified that English (United States) is selected as my localization.

**Comment by dmoonfire** [comment]
I thought that error message was only in the 1.12 branch. Is there a chance you have `spell-check-test` installed?

**Comment by lucascosti** [comment]
+1 for this. Also getting no spell checking and the console shows
`spell-check:en-us Can't load en_US: Cannot find dictionary for en_US.`

Running Atom 1.11.2 on Fedora 23, installed using the RPM directly from Atom. I don't have `spell-check-test` installed.

It is working fine in v1.10.2. Anything from 1.11.0 onwards has this issue.

**Comment by lucascosti** [comment]
@dmoonfire after doing some hunting, for my situation (linux) I think the problem may be this line:

https://github.com/atom/spell-check/blob/master/lib/system-checker.coffee#L62

On my system (Fedora 23), the dictionary files are in `/usr/share/myspell/`, not `/usr/share/myspell/dicts`.

**Comment by dmoonfire** [comment]
@cynicated: I've duplicated this one one of my Windows machines (Windows 7) but not on my Windows 10 machine. There is a chance the probelm is in the core library we use but I need to investigate it further before I can say for sure. Windows spellchecking is... different from the others in that it doesn't point directly to `.dic` files but uses the built-in spell-checking.

@lucascosti: Awesome. You should be able to put it in the "Locale Paths" of the settings for `spell-check` and have it work. If it does, it just means I need to add it to the standard search paths. I do think it is a separate issue from this one, would you be willing to open a new issue and CC me? I think this one won't take long to push (unlike the one above).

Thank you both.

**Comment by lucascosti** [comment]
Thanks @dmoonfire, I didn't know there are now a lot more options in spell-check now! (as a tech writer, known words will be especially useful for me :))

Adding `/usr/share/myspell/` to the new locale paths setting got it working for me. I'll open a new issue as requested to get that added to the standard search paths.

**Comment by dmoonfire** [comment]
@lucascosti: Thank you. You might also check out my `spell-check-project` which creates a project-level known words dictionary. That could be useful for specific library and technical names that only apply to a single project. (This is also the entire reason I wanted to do #120).

**Comment by dmoonfire** [comment]
@cynicated: As a possible work-around, you could download the `en_US.dic` and related files to a simple path (say `C:\dicts`) and then set the path manually in the `spell-check` settings.

**Comment by cynicated** [comment]
@dmoonfire: No, I don't have `spell-check-test` installed.  

However, your suggestion of just downloading a dictionary package did seem to get things working for now.  Thanks!

**Comment by corsen2000** [comment]
@dmoonfire I followed your suggestion and it did get spell checking working, but it is now flagging all plural forms of words as invalid. For example `solution` is a word, but `solutions` is not.

I downloaded both `en_US.aff` and `en_US.dic` from https://github.com/atom/node-spellchecker/tree/master/spec/dictionaries. 

Any ideas?

Thank you.

**Comment by dmoonfire** [comment]
@corsen2000: Make sure it is `en_US.aff` and not `en_US.aff.txt`. Even though I renamed it, Chrome insisted on putting the `.txt` at the end of it which causes it not to load. Also, I was getting "solutions" as an error until I did rename it (and then change a setting to force a reload).

Alternatively, you can download Hunspell's dictionary at https://sourceforge.net/projects/hunspell/files/Spelling%20dictionaries/en_US/ which may give you better results. Again, make sure it is `.dic` and `.aff`, otherwise `spellchecker` can't find it.

**Comment by corsen2000** [comment]
@dmoonfire thanks for the tip. I was not able to get the `node-spellchecker` files to work, even trying what you suggested. Swapping in the Hunspell versions did fix the issue though.

**Comment by BugZappr** [comment]
I downloaded a fresh install of Atom, and ran into this issue too.  With some searching, and the above thread, I located my dictionaries in "C:\Users\User1\AppData\Local\atom\app-1.11.2\resources\app.asar.unpacked\node_modules\spellchecker\vendor\hunspell_dictionaries".  I tried setting this path in settings, no go.  I downed the dics at the above alternative link into "C:\dics", checked use locales, and set mine to en_US, and it worked.  I set mine back to the above long path in "C:\Users", and it worked.  It seems it works if the above path is set, the locale is set, and it is told to use locales.

**Comment by dukebarman** [comment]
I have a same bug on Windows 7 too

**Comment by dmoonfire** [comment]
I need to write some custom code to read into the ASAR for en_US dictionaries if one isn't provided. That will only work for en_US though. For everything else, setting locale search path and defining a language should always work. If I can find some standard paths in Windows 7, I could submit a path to check those first but Windows 7 doesn't seem to have a consistent place to put dictionaries (unlike Windows 10 which has them as a service).

**Comment by dukebarman** [comment]
In Windows 7 standard path for current user:
```
%LOCALAPPDATA%\atom\app-1.11.2\resources\app.asar.unpacked\node_modules\spellchecker\vendor\hunspell_dictionaries\
```

**Comment by dmoonfire** [comment]
The `app-1.11.2` changes for different versions of Atom. I found code that figures it out in the original `spellchecker` code, I just haven't had a chance to build Atom from scratch to prove it out with [my proposed fix](https://github.com/dmoonfire/spell-check/commits/search-default-path).

**Comment by nmontmarquette** [comment]
Hope I am not interrupting but here is how I resolved my own issue:

The Locales' setting mentions: "Examples would be en-us or de-DE..." I wasn't sure whether I had to put something or not. So I did enter en-us as suggested but on my CentOS7 system all of the dictionaries are spelled with an 'underscore' rather than a 'dash' character. So I replaced my 'Locales' setting from 'en-us' to 'en_US' ( as spelled on my system ) and for the first time the spell checker kicked in!

Now if I don't put something in the locale setting it seems to be looking for:
spell-check:us-en Can't load us_en: Cannot find dictionary for us_en. I understand that it my be based on something global on my CentOS system.

- I do have the latest Atom BETA ( 1.13.0-beta0 x64 )
- CentOS 7.2.1511
- The 'Locale Paths' settings I use '/usr/share/myspell/' or '/usr/share/myspell' works

```
[user@hypolita myspell]$ pwd
/usr/share/myspell
[user@hypolita myspell]$ ls
en_AG.aff  en_BS.dic  en_CA.aff  en_GB.dic  en_IE.aff  en_JM.dic  en_NG.aff  en_PH.dic  en_US.aff  en-ZM.dic
en_AG.dic  en_BW.aff  en_CA.dic  en_GH.aff  en_IE.dic  en_MW.aff  en_NG.dic  en_SG.aff  en_US.dic  en_ZW.aff
en_AU.aff  en_BW.dic  en_DK.aff  en_GH.dic  en_IN.aff  en_MW.dic  en_NZ.aff  en_SG.dic  en_ZA.aff  en_ZW.dic
en_AU.dic  en_BZ.aff  en_DK.dic  en_HK.aff  en_IN.dic  en_NA.aff  en_NZ.dic  en_TT.aff  en_ZA.dic
en_BS.aff  en_BZ.dic  en_GB.aff  en_HK.dic  en_JM.aff  en_NA.dic  en_PH.aff  en_TT.dic  en-ZM.aff
```

**Comment by i-apellaniz** [comment]
Instead you can do a symbolic link that also works for me: 
```
/use/share/myspell# ln -s ./ dicts
```

At the end I don't know which way is the best to patch this issue. But I'm fine with the link.

**Comment by dmoonfire** [comment]
@i-apellaniz: For yours, I've recently added https://github.com/atom/spell-check/pull/165 to include the default path in. That should fix your problem without links. I'm just waiting for a review and acceptance.

**Comment by 50Wliu** [comment]
Marking this bug as Windows-only from now on as #165 has been merged.

**Comment by Overdrivr** [comment]
Is there any workaround for Windows 7 ?

**Comment by karldw** [comment]
@Overdrivr, I had the same problem with Atom 1.16.0 on Windows 7.  The solution from @BugZappr worked for me.
Note that even though the Locale Paths text says "This is used for Linux and OS X", setting the Locale Paths also works for Windows.

**Comment by dqfan2012** [comment]
This is still a problem in Windows 7 for Atom 1.17.0 x64.

**Comment by mhenry07** [comment]
I had the issue as well using the zip binaries on Windows 7 (v1.19.4 x64). I had to use a different locale path from @BugZappr's [workaround](#issuecomment-255040870).

File > Settings > Packages > spell-check
* Use Locales: *checked*
* Locales: *empty*
* Locales Paths: `resources\app\node_modules\spellchecker\vendor\hunspell_dictionaries`

**Comment by migs911** [comment]
I need bilingual spell-check, so i use this settings (on Windows 7 too, atom v1.22.0-beta2 x64):

- Use Locales: checked
- Locales: **ru_RU,en_US**
- Locales Paths: resources\app\node_modules\spellchecker\vendor\hunspell_dictionaries

In that directory i have files: en_US.aff, en_US.dic, ru_RU.aff, ru_RU.dic

**Comment by OkumaScott** [comment]
I also have this issue. 
spell-check 0.72.2, atom 1.22.1, Windows 7 Enterprise
> system-checker.coffee:85 spell-check:en-us Can't load en-US: Cannot find dictionary for en-US.

"Use Locales" setting checked, and tried manually specifying locale to no avail.

**Comment by BugZappr** [comment]
Latest dictionaries here:
[SCOWL (and friends) | Files](https://sourceforge.net/projects/wordlist/files/speller/2017.01.22/)

**Comment by dycweb** [comment]
I'm late to the party...

On Windows 7 Pro, I had Atom 1.23.1 32-bit and discovered spell check wasn't working, though it had been at some point previously. I downloaded the latest dictionaries and changed the spell-check package settings based on advice in this thread. This worked for me:

File > Settings > Packages > spell-check

- Use Locales: checked
- Locales: empty
- Locales Paths: resources\app.asar.unpacked\node_modules\spellchecker\vendor\hunspell_dictionaries

Also, discovered that a 64-bit version of Atom has been available since early 2017. Installed that and can tell already that Atom is much faster now!

**Comment by nathansobo** [comment]
This will be fixed in 1.23.3, which should be release within the next couple days.

**Comment by philmikejones** [comment]
I still had this problem with v1.28.0 on Ubuntu. For Ubuntu users, I managed to solve it by opening System Settings > Language Support, then install the additional language settings when prompted (root required).

**Comment by miguelmena21** [comment]
Hola, la cosa esta en que añadan el idioma Ingles en su ordenador, así el Atom solucionara el error, ya que su idioma nativo es el ingles suele jalar datos en ese idioma y como no lo tenemos instalado es ahí en donde sucede el error. 

1. Se van directamente a inicio y escriben **Panel de control**
![captura de pantalla 1](https://user-images.githubusercontent.com/42123945/43849481-2bd8c588-9afb-11e8-8bb8-b40eb3e76cc4.png)
2. Eligen la opción **Reloj, idioma y región**
![captura de pantalla 2](https://user-images.githubusercontent.com/42123945/43849599-6f2c1650-9afb-11e8-890b-f5a9f8b5d11e.png)
3. En la opción "**Idioma**" le dan click en la parte inferior donde dice "_Agregar un idioma_"
![captura de pantalla 3](https://user-images.githubusercontent.com/42123945/43849687-a29a1442-9afb-11e8-9636-030f6eb862b3.png)
Solo buscan el idioma English (United States) y listo, se soluciona el error
![captura de pantalla 4](https://user-images.githubusercontent.com/42123945/43849691-a5413090-9afb-11e8-8567-0d1e9f12a762.png)

Espero les sirva, saludos

**Comment by aubreyz** [comment]
Still an ongoing problem. When you toggle spelling off, it then stays off regardless of any toggling. 

(On Windows 10, Atom and spell package up to date as of today)
