### ISSUE TITLE
accented characters on Linux (Fedora)

### ISSUE THREAD

**Issue by Briffou** [atom/spell-check#168]
I'm using Fedora 24 and atom 1.11.1 and I have troubles with spell-check and accented characters. 
I was aware that on Fedora I had to change the "Locale Paths" for dictionaries in spell-check package,
so i used /usr/share/myspell 
For "Locales" option in the setting of spell-check, I'm using "fr-FR, en-US". My LANG env variable is fr_FR.UTF-8 and all my documents are in UTF-8.

Now, when I write this in atom (none of this lines are real words) :
sjkfghhkfg
kloaoy vbvh
édjkghdkj
sdhjkghàsdf

First two lines are underlined in atom, which is correct, but last two lines -with accented characters- are not underlined, and that's the problem.
I'm also using a Mac and I have no troubles on the Mac, only on fedora. I also tried the last beta (1.12.0 beta 3) with no success. Any ideas, did I forgot something ?

oh, for info, I also launched hunspell in terminal on previous example, and everything works fine.
Thanks

**Comment by DamianPereira** [comment]
I can reproduce this issue too, do you have the problem described in issue 212?

https://github.com/atom/spell-check/issues/212

**Comment by Briffou** [comment]
Looks like I can't reproduce the issue in #212 , at least with fr_FR (I didn't try with es_ES). For instance, when I write "apres" (should be après), the word is underline and when I right click to correct everything works fine (i.e après is displayed). 
But in atom 1.18 beta 2 (fedora 24) I still have the issue that wrong accented words are ignored by spell-check, like aprèz.

**Comment by Briffou** [comment]
I'm closing this for the moment, since things started to work with atom-beta 1.20, can't really say why though.
