### ISSUE TITLE
Add known words in editor (menu item)

### ISSUE THREAD

**Issue by mysterytony** [atom/spell-check#171]
Is it possible to add a menu item in the context menu after right-clicking a wrong word? Instead of going to the setting panel to add words in "known words", I can just click and add the word to the dictionary.

Also, is it possible to add `ignore once` to the menu item so the word selected won't be marked wrong in that document?

**Comment by edwinksl** [comment]
Is this what checking the "Add Known Words" box supposed to do?

**Comment by mysterytony** [comment]
Yes, but it is not available on the right-click menu? You would need to go to setting and add the word in the textbox.

**Comment by edwinksl** [comment]
Ah okay, I checked the "Add Known Words" box and also didn't see anything new on the right-click menu, so I am not sure what checking it actually does.

**Comment by edwinksl** [comment]
Heh, I just noticed what it does. It is indeed working as intended.

**Comment by laniley** [comment]
I think it would help to put the "Add to known words" option in the right-click menu on top of the list.

**Comment by xpe** [comment]
With Atom 1.34.0 at least, if you want to have the "Add to Known Words" option available in your context menu, you will need to go to Atom's settings for the "spell-check" package and check "Add Known Words".

Clipped image from Atom settings:
<img width="440" alt="spell-check" src="https://user-images.githubusercontent.com/4576329/51505432-635f0080-1db4-11e9-9de9-652fc0e31d1b.png">

Example context menu (gotten by right-clicking):
<img width="223" alt="screen shot 2019-01-21 at 7 41 38 pm" src="https://user-images.githubusercontent.com/4576329/51505526-f009be80-1db4-11e9-91fc-938df0683a11.png">
