### ISSUE TITLE
-ise and -ize in en-GB

### ISSUE THREAD

**Issue by hamidohadi** [atom/spell-check#174]
Using current 'en-GB' locale words ending with -ize (eg. characterize, summarize, polarize etc.) are considered misspellings. These words, despite being seemingly American, are perfectly acceptable in British English too. Is there a reasonable way we could add them to the en-GB locale, without adding the whole en-US locale?

**Comment by thomasjo** [comment]
The actual dictionaries come from the OS. This package is merely a facilitator/proxy. Solving this needs to be done at the OS level.

Try googling around for ways to amend or customize locales, specific to your OS.
