### ISSUE TITLE
Spell-check Package does NOT work 

### ISSUE THREAD

**Issue by JIMMMY0** [atom/spell-check#186]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Misspelling a word produces no result;
spell-check package doen not work;
I have already followed the deugging process here http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode

Now what I do is pasting the whole document into Word and let it check my spellings :-)
but it's quite troule some if I have a large and complex file. 
Hope somebody could help me, thanks a lot! 

### Versions
1.12.7

**Comment by GafferMan** [comment]
Having the same issue. Spellcheck worked before, but has since stopped working. Does not work in "safe" mode either. I have not loaded any new packages.

**Comment by jacknlliu** [comment]
I met the same issue. It did not work with RPM package version 1.12.7.

**Comment by gncs** [comment]
I had the same issue (CentOS 7), but fixed it:
- make sure `hunspell` and `hunspell-en` are installed
- add `/usr/share/myspell` to `Locale Paths` in `spell-check` settings

**Comment by JIMMMY0** [comment]
Fixed finally by installing new dictionaries. Thanks every who helped me!
