### ISSUE TITLE
Feature request: Minimize number of clicks needed to get to correct word

### ISSUE THREAD

**Issue by rubin110** [atom/spell-check#188]
As encouraged through #29, I'm writing this feature request. As compared to other text editors it currently takes too many clicks/time in order to select a correction as a replacement with Atom.

Atom:
1. Double click incorrectly spelled word in order to highlight the whole word
2. Right click highlight
3. Move cursor all the way down to the Correct Spelling menu item that's at the bottom of the context menu
4. Click on the Correct Spelling menu item to have a new modal popup with a list of possible corrections
5. Click on the replacement correction

In total spell-check for Atom takes about 5 clicks and a bit of mouse moving and coordination to click in the right spots.

Libreoffice, Kate, MS Word, Google Doc, any text field within Google Chrome, any system text field in OS X:
1. Right click word
2. Highlight correction (generally located at the top of the context menu)
3. Click correction

Most other widely use text editors and word processors only take 2 clicks, no highlighting, and the available corrections are generally the first item on the context menu so there's minimal cursor movement.

I'm an extremely bad speller and a lot of times use my text editor of choice to draft up things before pasting them elsewhere. It would excruciatingly helpful if Atom's implementation of spell-check conformed to how a lot of other editors do it, by minimizing the number of clicks and mouse movement needed to get to a correction. This behavior at this point the only thing keeping me from using Atom more full time.

Thank you.

**Comment by 50Wliu** [comment]
This has been implemented by #172 in Atom 1.14.0, albeit that the suggestions show up at the bottom.  If you'd like them to show up at the top, please file a new issue and completely fill out the issue template, or **it will be closed**.  Thanks!
