### ISSUE TITLE
When I click "Settings", I can only see "README"

### ISSUE THREAD

**Issue by esrevinu** [atom/spell-check#191]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When I click "Settings", I can only see "README"

### Steps to Reproduce

1. I'm using win7 enterprise & Atom 1.14.2 & spell-check 0.70.2
2. I want to change the setting to make the spell-check enabled in my java file
3. When I click "Settings", I can only see "README" so I can't modify the settings
4. Actually even though I write the plain text the spell-check can't work.

**Expected behavior:** WORK

**Actual behavior:** CAN'T WORK

**Reproduces how often:** Each time

**Comment by rsese** [comment]
Can you share a screenshot of what you see right after clicking on the package Settings button @esrevinu?

**Comment by esrevinu** [comment]
Now I find the "Setting" button works. However, the spell-check still can't work.
![image](https://cloud.githubusercontent.com/assets/2812221/23009396/b9d21b08-f450-11e6-95c2-40ec9a349868.png)
My Setting Page:
![image](https://cloud.githubusercontent.com/assets/2812221/23009424/e1971f1c-f450-11e6-9626-99931ca11207.png)

**Comment by rsese** [comment]
> However, the spell-check still can't work.

Can you confirm if you see any console errors in developer tools (`Ctrl+Shift+I` then click `Console`)?

I wonder if you're running into https://github.com/atom/spell-check/issues/162.

**Comment by esrevinu** [comment]
Yeah, I've found the answer in #162 by downloading the dic and set the Locale Paths. Thanks a lot :+1:
