### ISSUE TITLE
Cannot reenable autocorrect keybindings after disabling them

### ISSUE THREAD

**Issue by CSFlorin** [atom/spell-check#194]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]
Cannot reenable keybinding because the setting disappears after disabling.
### Steps to Reproduce

1. [First Step] Disable keybindings.
2. [Second Step] Restart Atom
3. [and so on...] The option to reenable them has disappeared

**Expected behavior:** [What you expect to happen]
I expect that I could reenable them
**Actual behavior:** [What actually happens]
I am not able to reenable them
**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.
Those commands don't work for me.
### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by 50Wliu** [comment]
Closing in favor of atom/settings-view#946 as this is a Settings View issue, not a spell-check issue.  Thanks for contributing!
