### ISSUE TITLE
Correction dropdown fails to consistently gain focus on 1.16.0-beta0

### ISSUE THREAD

**Issue by benbalter** [atom/spell-check#197]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Spell check intention dropdown does not gain focus when keybinding is activated resulting in enter and up/down not properly working without clicking the dropdown.

### Steps to Reproduce

1. Create a makdown file with a misspelling
2. Put the cursor on the misspelled word
3. Hit CMD-SHIFT-;
4. See the list of corrections appear next to the word

**Expected behavior:** List of corrections has focus, allowing the user to press up/down to choose  the word and enter to insert it.

**Actual behavior:** List does not have focus. Enter inserts a new line. Up/down changes the pointer location within the document.

**Reproduces how often:** Sometimes this works on initial load, and may work a handful of times (1-3), but then fails to work for all words within the document.

### Versions

```
Atom    : 1.16.0-beta0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.14.1
npm  3.10.5
node 4.4.5
python 2.7.13
git 2.12.0
```

### Additional Information

Note, this is on Atom 1.16.0-beta0.

**Comment by Ben3eeE** [comment]
I can reproduce this on `1.17.0-dev-cd946d8`.

@benbalter Do you know if this started happening recently?

**Comment by benbalter** [comment]
> Do you know if this started happening recently

Yes. I use this feature daily. 90% sure this began when I upgraded to Atom 1.16 Beta.

**Comment by Ben3eeE** [comment]
@benbalter Thank you for the report :bowing_man: I can confirm that this is a regression. I am unable to reproduce using Atom 1.15.0.

**Comment by as-cii** [comment]
Thanks for the report @benbalter, and apologies for this issue! 🙇 

I will look into this tomorrow morning and cherry pick the fix onto beta, so that it can go out with the next hotfix release.
