### ISSUE TITLE
Text editors are not removed from global `spellCheckViews` object when they are destroyed

### ISSUE THREAD

**Issue by as-cii** [atom/spell-check#201]
This is causing a memory leak as you can notice from this heap snapshot:

![screen shot 2017-04-24 at 15 53 41](https://cloud.githubusercontent.com/assets/482957/25340492/3738d520-2906-11e7-9f78-b4342e511c58.png)

/cc: @iolsen

**Comment by driskell** [comment]
I'm seeing this also. I was wondering why everything was going extremely slow and I have many many TextEditors still held open by spell-check
