### ISSUE TITLE
Allow relative paths for Locale Path for Windows (possibly Linux and Mac as well)

### ISSUE THREAD

**Issue by ethernal** [atom/spell-check#203]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * [X] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * [X] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * [X] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
When installed via ZIP file (I am creating portable Atom installation) Atom on W7 requires to have full path to Locale's directory ex. E:\software\atom\dictionaries

where atom folder structure is:

atom
|- atom (main program)
|- .atom (user files)
|- dictionaries (dictionaries that should be used)

To get spell-check working I cannot use ..\dictionaries folder as Atom spell check stops working then.

Please note that this works also for Windows 10, so there is no real need to use W10 dictionaries if not needed (that is a good thing as user does not have to do anything to get spellcheck working in case of switching OS - it just works as it did before).

I may be using the relative path wrong (from Atom.exe point maybe starting point is different?)

### Steps to Reproduce

1. Get Spell Check working with absolute paths.
2. Change Locale Path to relative
3. Spell Check is broken now.

**Expected behavior:** Spell Check should work when using relative paths.

**Actual behavior:** Spell Check cannot find dictionaries.

**Reproduces how often:** 100%

### Versions

1.16 installed from ZIP

### Additional Information
If spell check should use different relative paths it should be noted in the settings description - this would help a lot.

**Comment by dmoonfire** [comment]
This was merged a while but I forgot to close the issue.
