### ISSUE TITLE
Add a way to choose the current language

### ISSUE THREAD

**Issue by jdhoek** [atom/spell-check#21]
When you're a software developer and your native language is not English, chances are that you will be switching a lot between English and your native language. I would like to be able to choose the language from my available spell check dictionaries.

The current workaround is to change the system dictionary, but that is cumbersome and most of the time I only want to change the language for the application I am working in at that moment.

On GNU/Linux graphical desktop environments applications that work with text all provide a way to either set the language of the text (Libre/OpenOffice) or to select the current language (Gedit, web browsers, etc.).

Firefox does this very nicely for example:

![switch_language](https://cloud.githubusercontent.com/assets/683699/3051261/311acbb6-e189-11e3-83d1-f75b8c469447.png)

Can we get this functionality in Atom? On GNU/Linux (I don't know about Windows, does it use Hunspell as well?) changing the user's locale is the only way to change the default dictionary language. This means that Atom's spell check is basically stuck in one language, even though multiple dictionaries are available.

It looks like https://github.com/atom/node-spellchecker provides an OS-agnostic interface for spell-checking (using either Hunspell or the system spell checker if you are using Mac OS X). Perhaps it is possible to add a call for a list of available languages as well?

**Comment by dpagano** [comment]
I use Atom to take notes in markdown format. I have to do so in different languages. 
Changing the system language when switching between two files?? No way. 
So currently I have to live with the curly lines and copy the "finished" document over to a different tool to do my checking. I think there are better ways.

**Comment by KillerJK** [comment]
Some of my files in English and others in a different language (although I'm trying to keep all of them in English). It would be nice if I could select the language used for the spell check in individual files. Auto detecting them would be better, but I don't know if that solution would be problematic, as previously discussed.
Actually, I would like to see project files that I could store, where this settings were saved. But that would be a different discussion.

**Comment by danielschmitz** [comment]
I'm write books in different languages and need to change language every time, i need this feature :)

**Comment by hellboy81** [comment]
+ `infinity`

**Comment by boopr** [comment]
I'm writing my gliding courses with Atom in french, but it corrects my text in english. I really need this feature too :+1:

**Comment by paulcbetts** [comment]
> Detecting languages automatically is quite error prone, especially in a programming context.

This isn't true, node-cld2 will very very accurately detect text as long as it is more than a sentence.

**Comment by jdhoek** [comment]
@paulcbetts 

Unfortunately, an algorithm cannot reliably distinguish between language variants. In fact, `cld` makes no attempt to so from what I can tell. It only detects the language (e.g., 'English' or `en`), it does not distinguish between language variants (e.g., `en_GB` and `en_US`). This is not good enough for a spell-checker, because spelling dictionaries *are* language-variant-specific.

Also, such local lingual idiosyncrasies are precisely why we like having spell-checkers in the first place. It is not very helpful if your editor claims "Nice color!" is correct English when you are actually writing text meant for a British audience. :smiley:

**Comment by paulcbetts** [comment]
lol, let's run before we can walk, right now Atom doesn't even do anything other than English

**Comment by ihatetothink** [comment]
Hello, I've written few lines that add a rough multi-language support, here is the repo. (wich I don't know if I created correctly, quite new here...)

https://github.com/ihatetothink/spell-check

Right now uses the status bar to choose from the system languages. 
It uses a variable inside each active editor which I don't know if it's a good idea. 
I'm neither confident of its architecture (even for such a small project!)

I'm still testing by the way... any word will be appreciated.

**Comment by Yaco** [comment]
Hi @ihatetothink, i tried your fork but coulnd't installed. After I clone it locally I need to install some Node moules (underscore-plus, spellchecker, atom-space-pen-views). Finally I got this error when I load Atom:

```
Uncaught Error: Module did not self-register.
ATOM_SHELL_ASAR.js:137
Hide Stack Trace
Error: Module did not self-register.
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:137:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:137:20)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/yaco/.atom/packages/node_modules/spellchecker/lib/spellchecker.js:2:16)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/opt/atom/resources/app.asar/src/compile-cache.js:190:21)
```

I am using Atom 1.2.0

Any clue?

**Comment by 50Wliu** [comment]
@Yaco you need to `apm install`, not `npm install`.

**Comment by Yaco** [comment]
Thx @50Wliu, still failing: 

```
$ apm install underscore-plus
Installing underscore-plus to /home/yaco/.atom/packages ✗
Request for package information failed: Not Found
```

**Comment by FredrikWendt** [comment]
+1 - disabling this plugin as it's just adding noise

**Comment by OJFord** [comment]
The above (now merged) PR changes the default spell check language to your system default - i.e. your `LANG` environment variable.

So while we still can't change the language on the fly, this has been a vast improvement for me, as I only really wanted my system `en_GB` anyway. If you did want to change to another language, you could set (`export LANG=xx_XX`) and restart Atom.

**Comment by sbrl** [comment]
@OJFord Thank you! When will that PR be realed as an update to spell-check?

**Comment by darobin** [comment]
@OJFord This is already a big improvement, cool. I couldn't find this in the docs: is there a way to run multiple Atom instances in parallel? It's not an ideal solution, but at least it would make it possible to run them with different `LANG` values.

**Comment by OJFord** [comment]
@sbrl No idea I'm afraid; hopefully the dependency will be updated in the next release.. you could [modify it](https://github.com/atom/spell-check/blob/master/package.json#L8) yourself to read `3.2.3`, and then run `npm update`. It would need doing again if `spell-check` was updated without this (or later) change though.

@darobin Yes, just export `LANG` and run `atom` alternately from terminal. (If you get 'command not found' or something for `atom` then I think you need to 'Install Shell Commands' - from the main 'Atom' menu on OS X).

**Comment by sbrl** [comment]
@OJFord Ah right. I'm not that desperate (although it sounds like a terribly useful change) - hopefully the next release isn't too far away.

**Comment by OJFord** [comment]
I've submitted a PR to specifically address it, otherwise I suppose there may be no reason for anyone to think it was worth updating it for some time.

**Comment by OJFord** [comment]
This is now merged and released in v0.67.0 - @sbrl

**Comment by sbrl** [comment]
@OJFord Awesome, thanks!

**Comment by OJFord** [comment]
FYI @sbrl @darobin this is in Atom 1.7.x, so you can use it now in the beta releases, or hopefully not wait too much longer before stable reaches 1.7.

**Comment by sbrl** [comment]
@OJFord Thanks! I'm using stable. Not too long now!

**Comment by MAWSpitau** [comment]
I installed the current beta right now, but I am not able to find any language suggestions...

**Comment by RackhamLeNoir** [comment]
I have Atom 1.23.0, and I still can't switch languages manually. 
Automatic detection can be useful in some cases. But most of the time, I'm damn better than any algorithm at knowing what language I would like to spell check.

**Comment by x0s** [comment]
Here is how I manually switch between system default language (English for me) and others (French for example) on Ubuntu/Atom
- If you don't already have dictionary in your system:
    - look for it [here](https://packages.ubuntu.com/search?keywords=hunspell)
    - Install it browsing this URL (example with french): ` apt://hunspell-fr`
- Add new locale in _Locales_ field under _spell-check_ settings in Atom. The new locale to write is the hunspell suffix (**fr** in our example)
- Open a text file(markdown for instance), and the curly lines should be gone except for your typing errors ;)
