### ISSUE TITLE
Strange race condition in tests

### ISSUE THREAD

**Issue by lee-dohm** [atom/spell-check#239]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Tests are failing when running on Travis or when running locally on macOS 10.13.3. Tracked it down to a race condition in the testing framework, apparently.

### Steps to Reproduce

1. Comment out these lines: https://github.com/atom/spell-check/blob/master/spec/spell-check-spec.coffee#L46-L53
2. Run tests and verify they all pass
3. Uncomment those same lines
4. Run tests

**Expected behavior:** All tests pass

**Actual behavior:** All tests time out

**Reproduces how often:** 100%

### Versions

```
Atom: 1.26.0-dev-429f2bdd0
Electron: 1.7.11
Chrome: 58.0.3029.110
Node: 7.9.0
```

```
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.26.0-dev-429f2bdd0
python 2.7.10
git 2.16.2
```

### Additional Information

N/A

**Comment by as-cii** [comment]
After #240 tests seem to be more reliable. Closing this for now.
