### ISSUE TITLE
What dictionary is used on Ubuntu?

### ISSUE THREAD

**Issue by detly** [atom/spell-check#26]
I am using Atom 0.120.0 (built from the release tag) on Ubuntu 14.04. The spellchecker will highlight, say, `colour` but not `color`, which suggests it's using US English instead of Australian English.

My system settings are to use Australian English for UI translations.The only relevant environment variables I can see are:

```
LANG=en_AU.UTF-8
LANGUAGE=en_AU:en
```

The `README` says:

> This package will use the dictionary set by the system.

...but on it's not really clear what that means for Ubuntu. Is it `aspell`? Or `hunspell`? Or `myspell`? Or something else?

**Comment by jakkul** [comment]
I experience the problem as well. I cannot find a way to set PL language for spellchecking. en_US seems to work OK with no configuration whatsoever.

My locale variables:

echo $LANG
pl_PL.UTF-8
echo $LANGUAGE 
pl

**Comment by bentolor** [comment]
Stumbling over the same issue: As german developer I mostly write a mixture of English & German. So switching should be easy, even better you should be able to select multiple languages as proposed in #11

**Comment by kevinsawicki** [comment]
Closing in favor of #11
