### ISSUE TITLE
Solución al error: Cannot load the system dictionary for en_US.

### ISSUE THREAD

**Issue by ghost** [atom/spell-check#264]
Hola, la cosa esta en que añadan el idioma Ingles en su ordenador, así el Atom solucionara el error, ya que su idioma nativo es el ingles suele jalar datos en ese idioma y como no lo tenemos instalado es ahí en donde sucede el error.

Se van directamente a inicio y escriben **Panel de control**, en el buscador y dan click sobre el
![captura de pantalla 1](https://user-images.githubusercontent.com/42123945/43850310-3af7be32-9afd-11e8-9a02-1a3cc9798806.png)
Eligen la opción **"Reloj, idioma y región"**
![captura de pantalla 2](https://user-images.githubusercontent.com/42123945/43850331-48121e82-9afd-11e8-967e-8a7cdf60004b.png)
En la opción **"Idioma"** le dan click en la parte inferior donde dice "Agregar un idioma"
    ![captura de pantalla 3](https://user-images.githubusercontent.com/42123945/43850341-50c94abe-9afd-11e8-8735-65512dc46c4c.png)
Solo buscan el idioma _English (United States)_ y listo, se soluciona el error
![captura de pantalla 4](https://user-images.githubusercontent.com/42123945/43850385-682ea334-9afd-11e8-8e32-9369ab21c893.png)

Preferiblemente instalen el Idioma _English (United States)_ ya que ese es el idioma original que solicita el Atom.

Suerte amigos.

**Comment by PCHL1970** [comment]
Perfecto, muchas gracias.

**Comment by dmoonfire** [comment]
Since there hasn't been any response for a while, I'm going to close this issue. Feel free to reopen.
