### ISSUE TITLE
spell check error while creating new file 

### ISSUE THREAD

**Issue by official-akshayjadhav** [atom/spell-check#275]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Editor shows spell check error I creates a new file.

### Steps to Reproduce

1. open editor.  
2. create new file.  
3. editor shan ows error of spell check.

### Versions
atom version: atom 1.30.0
apm version:  apm  1.19.0
npm version:  3.10.10
python version:  2.7.15rc1
git version: 2.17.1
OS: linux Ubuntu [ 18.04 LTS bionic ]

**Comment by Arcanemagus** [comment]
Could you share with us the error you are seeing?

Also please _directly_ copy and paste the output of `atom --version` and `apm --version` from the command line as requested in the template. There is additional information there that helps us diagnose issues.
