### ISSUE TITLE
Let spell-check skip URLs

### ISSUE THREAD

**Issue by DorKeinath** [atom/spell-check#277]
Is it possible to let the spell-check skip URLs? If not, this feature would be nice!

**Comment by dmoonfire** [comment]
@DorKeinath: Could you please try the `spell-check-urls` package and see if that works for you? If there is a URL that doesn't, let me have an example and I can look into it. That package is a small plugin for `spell-check` that just blindly accepts URLs.

**Comment by DorKeinath** [comment]
Magnificent. That's exactly what I was looking for. Thank you a lot for that plugin!
