### ISSUE TITLE
Spell check not finding dictionaries (macOS Mojave)

### ISSUE THREAD

**Issue by bojanisc** [atom/spell-check#279]
The spell-check addon does not find a local dictionary, even though the system sees it, and I have even hunspell (and cocoAspell) installed.

The error message is:

spell-check:hr-hr The package `spell-check` cannot load the system dictionary for `hr-HR`. See the settings for ways of changing the languages used,  resolving missing dictionaries, or hiding this warning.

The plugin checked the following paths for dictionary files:
* /Users/user/Library/Spelling
* /
* /System/Library/Spelling
* /Applications/Atom.app/Contents/Resources/app.asar/node_modules/spellchecker/vendor/hunspell_dictionaries

Which files does the addon try to find?

The /Users/user/Library/Spelling directory contains the hr_HR.aff and hr_HR.dic files.
It can be even checked with local hunspell (installed with brew):

$ hunspell -D
SEARCH PATH:
.::/usr/share/hunspell:/usr/share/myspell:/usr/share/myspell/dicts:/Library/Spelling:/Users/bojanz/.openoffice.org/3/user/wordbook:/Users/bojanz/.openoffice.org2/user/wordbook:/Users/bojanz/.openoffice.org2.0/user/wordbook:/Users/bojanz/Library/Spelling:/opt/openoffice.org/basis3.0/share/dict/ooo:/usr/lib/openoffice.org/basis3.0/share/dict/ooo:/opt/openoffice.org2.4/share/dict/ooo:/usr/lib/openoffice.org2.4/share/dict/ooo:/opt/openoffice.org2.3/share/dict/ooo:/usr/lib/openoffice.org2.3/share/dict/ooo:/opt/openoffice.org2.2/share/dict/ooo:/usr/lib/openoffice.org2.2/share/dict/ooo:/opt/openoffice.org2.1/share/dict/ooo:/usr/lib/openoffice.org2.1/share/dict/ooo:/opt/openoffice.org2.0/share/dict/ooo:/usr/lib/openoffice.org2.0/share/dict/ooo
AVAILABLE DICTIONARIES (path is not mandatory for -d option):
./hr_HR
/Users/user/Library/Spelling/hr_HR

Additionally, applications like textEdit support both Croatian (Library) and Croatian (Aspell), but Atom's spell-check still fails.

**Comment by bojanisc** [comment]
Bump ... No comments for this?

**Comment by meshosk** [comment]
Same problem here. 

Running `hunspell -D`:
```
Warning: Failed to set locale category LC_NUMERIC to en_SK.
Warning: Failed to set locale category LC_TIME to en_SK.
Warning: Failed to set locale category LC_COLLATE to en_SK.
Warning: Failed to set locale category LC_MONETARY to en_SK.
Warning: Failed to set locale category LC_MESSAGES to en_SK.
SEARCH PATH:
.::/usr/share/hunspell:/usr/share/myspell:/usr/share/myspell/dicts:/Library/Spelling:/

....

AVAILABLE DICTIONARIES (path is not mandatory for -d option):
/Library/Spelling/Slovak
/Users/user/Library/Spelling/sk_SK
```

I`ve got dictionaries in:
```
/Library/Spelling
/Users/[user]/Library/Spelling
```
In this dirs are `Slovak.aff`, `Slovak.dic`, `sk_SK.aff` and `sk_SK.dic` files. I set _locale paths_  value to `/Library/Spelling/, ~/Library/Spelling/` and set _locales_ value to `sk_SK, Slovak`.

Running atom results to same:
```
spell-check:sk-sk The package `spell-check` cannot load the system dictionary for `sk_SK`. See the settings for ways of changing the languages used,  resolving missing dictionaries, or hiding this warning.

The plugin checked the following paths for dictionary files:
* /Library/Spelling/
* /Users/[user]/Library/Spelling/
* /
* /System/Library/Spelling
* /Applications/Atom.app/Contents/Resources/app.asar/node_modules/spellchecker/vendor/hunspell_dictionaries
```
```
spell-check:slovak The package `spell-check` cannot load the system dictionary for `Slovak`. See the settings for ways of changing the languages used,  resolving missing dictionaries, or hiding this warning.

The plugin checked the following paths for dictionary files:
* /Library/Spelling/
* /Users/[user]/Library/Spelling/
* /
* /System/Library/Spelling
* /Applications/Atom.app/Contents/Resources/app.asar/node_modules/spellchecker/vendor/hunspell_dictionaries
```
Atom: 1.40.0 
os: Mojave 12.14.6

Using spell-check via __linter-spell__ package works.

Noticed:
Why plugin search in dir `/`? Also I do not have dir `/System/Library/Spelling` present

**Comment by jonohewitt** [comment]
I'm having this issue with en_GB on MacOS Catalina

**Comment by dmoonfire** [comment]
@bojanisc, are you still having issues with the latest version of Atom? We've had some recent changes related to looking for dictionaries. "Use System" in the current is what you want for Macs.

**Comment by dmoonfire** [comment]
Since there hasn't been any response for a while, I'm going to close this issue. Feel free to reopen.
