### ISSUE TITLE
The package spell-check cannot load the system dictionary for en_IN

### ISSUE THREAD

**Issue by maubenferie** [atom/spell-check#284]
Hi,
I get the following message as soon as Atom starts on linux lite os.

The package spell-check cannot load the system dictionary for en_IN. See the settings for ways of changing the languages used, resolving missing dictionaries, or hiding this warning.

Thanks and regards,
Mauben

**Comment by dmoonfire** [comment]
I'm not familiar with Linux Lite OS. Do you know where they store the `.dic` and `.aff` files? It may be a case of not searching in the default locations.

**Comment by jhabdas** [comment]
Dupe with #290

**Comment by Gowtham-Sridhar** [comment]
Please check out this link. It could be helpful

https://stackoverflow.com/questions/50963175/atom-cannot-load-the-system-dictionary-for-en-in-checked-the-following-paths-f

**Comment by divyanshk7** [comment]
1. Go to  Atom ->Edit ->Preferences ->Packages.
2. Then search for "spell check" and deselect Use Locales button and mention en-US(editor support language) in custom bar.

![Issue_github#284](https://user-images.githubusercontent.com/42926672/71760428-87dbbc00-2ee3-11ea-8164-0282a42f5f16.png)

3. Then restart atom.

Now you will get no such message.

**Comment by 9994444ggg** [comment]
Thank You for Help me. And a Happy New Year

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: Divyansh Kogta<mailto:notifications@github.com>
Gesendet: Samstag, 4. Januar 2020 06:47
An: atom/spell-check<mailto:spell-check@noreply.github.com>
Cc: Subscribed<mailto:subscribed@noreply.github.com>
Betreff: Re: [atom/spell-check] The package spell-check cannot load the system dictionary for en_IN (#284)


  1.  Go to Atom ->Edit ->Preferences ->Packages.
  2.  Then search for "spell check" and deselect Use Locales button and mention en-US(editor support language) in custom bar.

[Issue_github#284]<https://user-images.githubusercontent.com/42926672/71760428-87dbbc00-2ee3-11ea-8164-0282a42f5f16.png>

  1.  Then restart atom.

Now you will get no such message.

**Comment by dmoonfire** [comment]
@maubenferie: Are you still having this problem with the latest version of Atom?

**Comment by dmoonfire** [comment]
Since there hasn't been any response for a while, I'm going to close this issue. Feel free to reopen.
