### ISSUE TITLE
Spell Checker wrong underline

### ISSUE THREAD

**Issue by darkpal** [atom/spell-check#285]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Spell checker underlines correct words.

### Steps to Reproduce

1. Open a new file for editing
2. Paste a text. For example "The matching username is not an LDAP user or it is not in the same LDAP server"
3. Spell check

**Expected behavior:** All the words are correct

**Actual behavior:** These words are underlined: matching, username, same

**Reproduces how often:** 100%

### Versions

Atom 1.33.0 x64
MacOS 10.14.1

### Additional Information
The same text is correct in default MacOS 10.14 TextEdit app . Here is the screenshot
https://goo.gl/q38oCc

**Comment by darkpal** [comment]
**rsese** Yes, ru-Ru and en-US

I use spell checker with multiple languages in Notepad++ and it works perfectly https://goo.gl/a9kHJM

**Comment by rsese** [comment]
Thanks for confirming :+1:

> Note that Russian and English languages have totally different characters and maybe it's not the same problem as for example "de-DE and en-US"

Yeah not sure but I do see that the end result looks the same as you described with your settings:

![multiple-locales-spelling](https://github-slack.s3.amazonaws.com/monosnap/test-spell-locales.txt__worktest-tree-sitter_2018-12-05_17-57-53.png)

At least for the moment, it looks close enough to https://github.com/atom/spell-check/issues/230 that we'll close in favor of that issue for now if you want to subscribe there.  If what you're observing is a different issue, we can always re-open.
