### ISSUE TITLE
Correct spelling via context menu

### ISSUE THREAD

**Issue by dmnd** [atom/spell-check#29]
I saw misspelt something but hadn't read the instructions for this package. I tried to right-click on the misspelt word, but there was no way to correct the spelling there. A context menu for spelling would be much more discoverable than the current command/key binding. IME that's what most spell checkers do.

**Comment by LukeXF** [comment]
Would it not be possible to move the correct spelling to inside the first right click menu, rather than having to click, move mouse, click, choose word, click.

I just feel two click are much more standardised then going on a menu tree hunt for the word you want to correct.

**Comment by optikalefx** [comment]
+1 This is very inefficient for the user to have to click a 2nd option when everywhere else on my mac corrects spelling in the context menu. example 
![image](https://cloud.githubusercontent.com/assets/926885/10123259/4fcd1d1c-6503-11e5-9d9d-0be479a5ddf6.png)

**Comment by michaelajax** [comment]
Another +1

This really should work like the example by @optikalefx

**Comment by LukeXF** [comment]
Exactly, thanks @michaelajax and @optikalefx for reiterating my point.

Would love to see this feature changed to the suggested method.

**Comment by Midafi** [comment]
Yes +1. 

I like that Atom is doing something a bit different (especially I like the keyboard shortcut spelling correction UI). However two-click spellchecking via rightclick menus is so standard across platforms and programs that it should at least be an option I think.

**Comment by kleinbottle** [comment]
+1. What is requested above is the default behaviour in the kate and kile editors in KDE. In the interest of efficiency, I hope it gets adopted and implemented in atom.

**Comment by colinbrislawn** [comment]
+1 for implementing spell check in the standard way. This second menu adds an unnecessary step and is frustratingly inconsistent. 

I'm having a great experience using Atom and hope to see this fixed soon!

**Comment by dustinring** [comment]
Another +1
WTG @optikalefx

**Comment by Stephenitis** [comment]
+1

**Comment by cagmz** [comment]
+1

**Comment by LukeXF** [comment]
I think for a better user experience this issue should be reopened please @dmnd

**Comment by optikalefx** [comment]
I plus oned a year ago, I'll keep my plus 1 today.

**Comment by JoshuaRogan** [comment]
+1

**Comment by LukeXF** [comment]
Does anyone from Atom actually support their product anymore? It's been over a year and there is still not official response since myself and 10 other people commented on this issue. Come on guys...

**Comment by optikalefx** [comment]
Sometimes I feel like Atom was this cool project that people tried out, then after a while everyone went back their old ways

**Comment by 50Wliu** [comment]
@LukeXF there has been no response for two reasons.
1. The feature asked for by @dmnd already exists.  What you're asking for is different and doors not belong in this issue.
2. There already exists an open issue for your feature request: #54.

Yes, this could have been communicated better but there is absolutely no reason to ever expect an "official" response.

**Comment by LukeXF** [comment]
@50Wliu Thank you for a response, now time to support 54

**Comment by rubin110** [comment]
It's a little bothersome that I dropped Kate for Atom only to find that the development communicate is a little lacking in responding to feature requests like these. Even if the response is as simple as, "sounds nice but not on the road map for now."

So yeah I'm in the same bucket, as my spelling is horrible and use my text editor to draft up things in English all the time. Having the spell check involve a couple extra clicks (and remembering to do that) is a huge inconvenience and enough for me to switch back to Kate.

**Comment by 50Wliu** [comment]
As I said, what was asked for in this issue has been implemented _since spell-check was released_.  This issue is not the place to voice criticism over the existing implementation - if you would like to do that, please file a new issue.
