### ISSUE TITLE
Persist Language Warning

### ISSUE THREAD

**Issue by jhabdas** [atom/spell-check#292]
When a new locale is added and opened within the editor a warning alert may appear as described in the `README`. But it doesn't stay up long enough to be useful. Please persist it or change the error type. Thanks.

**Comment by jhabdas** [comment]
<img width="945" alt="screen shot 2019-01-10 at 5 38 22 pm" src="https://user-images.githubusercontent.com/440298/50959718-8eb53600-14fe-11e9-9fb9-9ac658b19066.png">

This could use some Wiki instructions too, platform-specific.

**Comment by jhabdas** [comment]
After further use the UX is spot on.

**Comment by rsese** [comment]
You can also use the `Notifications: Toggle Log` command to see a history of errors, warnings, etc.  Useful for things like this or if you accidentally dismiss a notification.
