### ISSUE TITLE
Problem with czech special symbols

### ISSUE THREAD

**Issue by Kattnienika** [atom/spell-check#306]
Hello,

I have problem with this plugin. The plugin identifies all words with Czech characters as bad. Ext. ěščřžýáíé. And it offers me a fix with bad characters.
![Snímek obrazovky pořízený 2019-05-12 10-29-28](https://user-images.githubusercontent.com/49788925/57579754-e9f13800-74a0-11e9-9514-1d18b0a80a5f.png)

**Comment by rsese** [comment]
Thanks for the report - this sounds like https://github.com/atom/spell-check/issues/241 I think, can you confirm if 1.37 (currently in beta) resolves this issue?  /cc https://github.com/atom/spell-check/issues/241#issuecomment-482722315

Also, please fill out the issue template when opening issues - the information in the template is super helpful when triaging issues.

**Comment by Kattnienika** [comment]
Yes, in Atom Beta is ok. When will the fix be available in a stable version?

**Comment by rsese** [comment]
Thanks for confirming!  Going to go ahead and close since the fix is merged.

> When will the fix be available in a stable version?

We don't have a specific release schedule but 1.37 stable just shipped today ⚡️ 

https://blog.atom.io/2019/05/12/atom-1-37.html
