### ISSUE TITLE
Alternative dictionaries under Windows7 absurdly complex

### ISSUE THREAD

**Issue by Queex** [atom/spell-check#311]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Setting a non-US language for the spellchecker on Windows systems before Windows 8 is close to impossible.

### Steps to Reproduce

1) Set any locale in the settings window for the package.
2) Observe the error saying the dictionary cannot be found.
3) Realise that there is no simple way to download any alternative dictionary.

No guidance is given in the spellchecker documentation itself, other than for Windows 8+. Further, googling readily-available downloads of alternative hunspell dictionaries only presents .deb packages, which cannot be opened easily on Windows systems.

It takes opening the developer console to even discover where to put any alternative dictionaries, and then you have to download them from the source on github, with no guidance from any of the documentation.

**Comment by rsese** [comment]
Thanks for the feedback - while we'd ideally like to provide extremely thorough documentation, after talking with the other maintainers, we've decided that documentation specific to Windows 7 isn't something we would prioritize creating now and it isn't something we would maintain in the future if changes are necessary.  For these reasons, we're going to close the issue but thanks again for the feedback.
