### ISSUE TITLE
Spell check issue across multiple lines

### ISSUE THREAD

**Issue by saivan** [atom/spell-check#313]
# Prerequisites

* [ x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

The spell check goes wrong and it's highlighting the whole line. This happens really frequently. 

### Steps to Reproduce

Just type the following into atom (I set it to safe mode just to be sure)

![image](https://user-images.githubusercontent.com/8543370/62169008-4f4f1980-b36a-11e9-9c4f-4bed0cc4b82b.png)

**Expected behavior:**

There are no spelling mistakes so I don't expect the red underlines.

**Actual behavior:**

Red underlines

**Reproduces how often:**

Always for this sentence, 
but its difficult to tell which sentences are causing this.

### Versions

Atom    : 1.39.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0

I'm on macOS Mojave (10.14.5)

**Comment by rsese** [comment]
Thanks for the report! I can reproduce with 1.41.0-nightly3 on macOS 10.14.6.

I noticed that it seems like the last newline is related?  When I remove the newline, the last sentence is no longer marked as misspelled:

![spellcheck](https://user-images.githubusercontent.com/734194/62172818-4b36e380-b2f9-11e9-81ad-b4343ebc5970.gif)

Similarly, if I leave the newline at the end of the file, removing the period at the end of the second sentence also unmarks the misspellings.

**Comment by saivan** [comment]
I don't know if it is. But I can say that I see it happen in the middle of files as well

**Comment by saivan** [comment]
Could be related to #281 perhaps. I can't see why it flags the whole line

**Comment by rsese** [comment]
> Could be related to #281 perhaps. I can't see why it flags the whole line

Oh yeah :+1:  Didn't see that issue, this seems really similar - I think we can close in favor of that issue for now and I'll mention it to the team.  If the issues are different, we can always reopen.
