### ISSUE TITLE
spel chek can't load

### ISSUE THREAD

**Issue by kracksyNL** [atom/spell-check#326]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

**Reproduces how often:**

**Comment by dmoonfire** [comment]
If you would be so kind, please check #328 since I'm in the process of resolving some of the spelling issues there. If not, please reopened this with additional details such as screen shots, error messages, or the contents of the console? Thank you.

**Comment by kracksyNL** [comment]
k

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

________________________________
Van: Dylan R. E. Moonfire <notifications@github.com>
Verzonden: Wednesday, May 13, 2020 3:07:19 AM
Aan: atom/spell-check <spell-check@noreply.github.com>
CC: kracksyNL <stefanb2016@outlook.com>; Author <author@noreply.github.com>
Onderwerp: Re: [atom/spell-check] spel chek can't load (#326)


If you would be so kind, please check #328<https://github.com/atom/spell-check/issues/328> since I'm in the process of resolving some of the spelling issues there. If not, please reopened this with additional details such as screen shots, error messages, or the contents of the console? Thank you.
