### ISSUE TITLE
Atom (Troubleshooting)

### ISSUE THREAD

**Issue by ArtioCode** [atom/spell-check#329]
Hello all

I'm fairly new to this, so forgive me if I'm posting in the wrong forum.

I am getting the below error when I open Atom and would welcome your thoughts...

The package spell-check cannot load the checker for en-GB. See the settings for ways of changing the languages used, resolving missing dictionaries, or hiding this warning.

Many thanks

AC

**Comment by CraigCottingham** [comment]
Duplicate of #328 ?

**Comment by dmoonfire** [comment]
This does appears to be a duplicate of #328 and I'm in the process of fixing it over there. I'm closing this, but feel free to reopen if you disagree.
