### ISSUE TITLE
Changes in settings are not persistent

### ISSUE THREAD

**Issue by pedrorrivero** [atom/spell-check#347]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Changes in settings go away once atom is restarted. In particular, new grammars, excludedScopes and known words are lost.

### Steps to Reproduce

1. Change spell-check settings (e.g. append `text.tex.latex` to the grammars list)
2. Restart atom

**Expected behavior:** Changes should be persistent.

**Actual behavior:** Changes are lost.

**Reproduces how often:** On restart.

### Versions

OS        : MacOS Catalina, Version 10.15.6
Atom    : 1.51.0
apm      : 2.5.0

### Additional Information

Editing the 'config.cson' file makes changes permanent, however I could not find proper documentation on the different options for this package. Also, the list of known words should not rely exclusively on manually editing said file, but on the GUI as well.

**Comment by darangi** [comment]
Hi @pedrorrivero , are you still experiencing this issue? I tried reproducing this but I couldn't. Have you tried running atom in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?

**Comment by pedrorrivero** [comment]
I was still experiencing the issue. Strangely enough, I tried safe mode and it worked fine. Then I went back to normal mode and only then the problem seemed to be fixed. I do not know what that was all about. But it works okay now. Thank you so much for the support!
