### ISSUE TITLE
spell-check source code

### ISSUE THREAD

**Issue by Alghamdi** [atom/spell-check#35]
Is it possible to get this package to spell check source code, like checking spelling mistakes for variables?

**Comment by ricardograca** [comment]
Probably stupid question, but what exactly is this package spell-checking anyway? It seems that from all my project files only markdown is being spell-checked.

**Comment by ricardograca** [comment]
Ok, to answer my own question it seems it only spell-checks Markdown, Plain Text and Commit Messages.

**Comment by lee-dohm** [comment]
@ricardograca It is a comma separated list of scope names. So if you wanted it to spell check HAML files, you could go to the [language-haml package](https://atom.io/packages/language-haml) in your Settings View, open the settings for it and find the scope there:

![scope-name](https://cloud.githubusercontent.com/assets/1038121/6082554/31093494-add7-11e4-92e0-d524b8eaf658.png)

**Comment by ricardograca** [comment]
Thanks @lee-dohm :) However, it seems that writing anything in that field overrides the defaults, and it's not possible to copy the defaults, so I would have to write them down and then manually write them again together with the new options. That's slightly less than ideal :)

**Comment by lee-dohm** [comment]
@ricardograca *That* is covered by atom/settings-view#243 :grinning:

**Comment by Cipa** [comment]
It works now for php, but not for tpl(do you want me open a new issue?)

For tpl I tried
text.html.tpl, text.html.*, text.html

From my experience I had to copy the default 
"default": ['source.asciidoc', 'source.gfm', 'text.git-commit', 'text.plain', 'text.plain.null-grammar']

strip it of ' and [, so the final string to be entered

text.html.php, source.asciidoc, source.gfm, text.git-commit, text.plain, text.plain.null-grammar

**Comment by Cipa** [comment]
I think this is related
Spell Check should at least spell check the string variables
In my example xauthorities is only spellchecked on the first line not where the errors array is initialized. 

![screen shot 2015-02-13 at 12 44 04 pm](https://cloud.githubusercontent.com/assets/293377/6192263/1aa2cb6e-b37e-11e4-9254-7cc440341580.png)

**Comment by Alghamdi** [comment]
Thanks @lee-dohm.
