### ISSUE TITLE
Underlines appear under blank space / wrapped space

### ISSUE THREAD

**Issue by Moter8** [atom/spell-check#43]
![1](http://i.imgur.com/3wGnp20.png)

And when I make the window wider again:

![2](http://i.imgur.com/Nqhgegl.png)

```
'global':
  'exception-reporting':
    'userId': '84c65616-dd5b-347b-3d53-50153c0eb9a2'
  'welcome':
    'showOnStartup': false
  'core': {}
  'editor':
    'invisibles': {}
  'spell-check': {}

spell-check 0.45.0
atom 0.165.0
```

**Comment by lee-dohm** [comment]
Per discussion on atom/atom#4842, I'm going to close this since the bug appears to be in the Decorations API, not in the spell-check package itself.

Thank you very much for reporting and including such detailed information!
