### ISSUE TITLE
Q: spell-checking does not highlight anything (but suggests corrections if prompeted)

### ISSUE THREAD

**Issue by dengemann** [atom/spell-check#45]
Hello folks, I'm trying to troubleshoot the behavior of spell-check on a Yosimite Macbook Air 11' with the most recent Atom version. While system spell checking seems to work e.g. in TextMate I don't see any words highlighted when e.g. opening a plain text file. Prompting corrections works however. Any suggestions where I should start searching for the solution?

**Comment by jekriske** [comment]
Same issue here. The plugin is not highlighting spelling errors under OSX 10.10 Yosemite.
![screen shot 2015-01-07 at 11 54 51 am](https://cloud.githubusercontent.com/assets/3432769/5649473/0e3354a2-9664-11e4-9cb2-c2d585c161d2.png)

**Comment by lee-dohm** [comment]
I suspect this was fixed in e155e85d259d1157840f15e436aa6e2113c06091, which I believe was included in the latest Atom release, v0.168.0. Upgrade to the latest version and let us know if that does not fix it.

Thanks for reporting the issue!

**Comment by dengemann** [comment]
Yes, I can confirm, all is fine again with 0.1.68.0. Thanks for the quick
feedback.

2015-01-08 5:36 GMT+01:00 Lee Dohm <notifications@github.com>:
