### ISSUE TITLE
Doesn't work for .tpl files on Mac

### ISSUE THREAD

**Issue by Cipa** [atom/spell-check#48]
Atom  Version 0.179.0 (0.179.0)
Spell Check 0.54.0

Seems to be working for untitled new tabs for me.

![screen shot 2015-02-13 at 9 41 48 am](https://cloud.githubusercontent.com/assets/293377/6188950/8e1e5460-b364-11e4-9214-0ea96ce6ad8c.png)

**Comment by izuzak** [comment]
See the README:

https://github.com/atom/spell-check/blob/master/README.md#spell-check-package-

> By default spell check is enabled for the following files:

> Plain Text
> GitHub Markdown
> Git Commit Message

> You can override this from the Spell Check settings in the Settings view (cmd-,).

**Comment by Cipa** [comment]
Hi, 

I can't seem to find a way to enable it for other file types when I press cmd-,
Should I see a Spell Check section?

**Comment by izuzak** [comment]
Settings for specific packages are available when you view those packages in Settings View. After you open Settings View, go to Packages and then find the spell-check package there and click on the "Settings" button for that package.

![screen shot 2015-02-13 at 15 52 00](https://cloud.githubusercontent.com/assets/38924/6189109/4763ebc8-b398-11e4-9044-f10ecd9345a9.png)

**Comment by Cipa** [comment]
It's still not clear to me what I have to enter in that Grammars box, 
I my case 
```text.tpl, text.php``` or  ```'text.php', 'text.tpl'``` or ```['text.php', 'text.tpl','source.asciidoc', 'source.gfm', 'text.git-commit', 'text.plain', 'text.plain.null-grammar']```
don't work, do I have to restart?

If it's not too much to ask maybe the instruction to how to set it up could be improved.

**Comment by izuzak** [comment]
@Cipa does this comment help: https://github.com/atom/spell-check/issues/35#issuecomment-73260699 ?

You should enter a comma-separated list of scopes, and you can find the scope you need to input in the settings of the language package which is parsing the .tpl file in question (personally, I've never used .tpl files so I'm not sure which language is responsible for it).

> If it's not too much to ask maybe the instruction to how to set it up could be improved.

Please feel free to open another issue for that.

**Comment by Cipa** [comment]
.tpl is just a regular html file. I don't use .html for security(Apache is not supposed to show .tpl files) and to show that the file is included in another file.

I will have a look at the above

Thanks

**Comment by Cipa** [comment]
It works now for php, but not for tpl(do you want me open a new issue?)

For tpl I tried
text.html.tpl, text.html.*, text.html

From my experience I had to copy the default 
"default": ['source.asciidoc', 'source.gfm', 'text.git-commit', 'text.plain', 'text.plain.null-grammar']

strip it of ' and [, so the final string to be entered

text.html.php, source.asciidoc, source.gfm, text.git-commit, text.plain, text.plain.null-grammar

**Comment by izuzak** [comment]
No need to open a new issue, just provide the following details in a comment on this issue:

1. a link to a [gist](https://gist.github.com) with the .tpl file in question
2. a screenshot which shows the settings for spell-check which you used
3. a screenshot which shows the file in Atom
4. a clear description of what part of the file you expected the spell-check to catch as an error

**Comment by Cipa** [comment]
Gist here: https://gist.github.com/Cipa/96b3f9a6d7e9bfc90001

Some screenshots

![screen shot 2015-02-13 at 11 13 14 am](https://cloud.githubusercontent.com/assets/293377/6190655/7bed8862-b371-11e4-9336-4a80fe7f2fb7.png)
![screen shot 2015-02-13 at 11 13 03 am](https://cloud.githubusercontent.com/assets/293377/6190657/7bee7f74-b371-11e4-8099-f447586fee09.png)
![screen shot 2015-02-13 at 11 12 53 am](https://cloud.githubusercontent.com/assets/293377/6190656/7bee66ec-b371-11e4-9673-ff98b4d7de28.png)

**Comment by izuzak** [comment]
This works for me:

![screen shot 2015-02-13 at 17 18 03](https://cloud.githubusercontent.com/assets/38924/6190736/55e8b3c0-b3a4-11e4-87f1-a22dda6e098a.png)

**Comment by Cipa** [comment]
That works, thank you
