### ISSUE TITLE
spellcheck not activating if word is next to "

### ISSUE THREAD

**Issue by Cipa** [atom/spell-check#49]
If a word is next to " the spellcheck underline fails to appear.

![screen shot 2015-02-13 at 2 44 38 pm](https://cloud.githubusercontent.com/assets/293377/6194096/fd7f074e-b38e-11e4-9816-b8cf277a08c8.png)
![screen shot 2015-02-13 at 2 45 58 pm](https://cloud.githubusercontent.com/assets/293377/6194105/0c10174e-b38f-11e4-9ea4-aa7b1ed8753d.png)

**Comment by Alghamdi** [comment]
Reproduced spellchecking python
![python_spell_check](https://cloud.githubusercontent.com/assets/461753/6215918/e3a0e494-b5fc-11e4-83bb-817ad4dadc9c.png)
