### ISSUE TITLE
Not working on linux?

### ISSUE THREAD

**Issue by TheChymera** [atom/spell-check#52]
So, how can I make this work on my linux machine? it is enabled, and under its "Settings" section I see a `Default: ...` list of grammars, but it does not highlight a single (misspelled) word. 

Could you help me out?

**Comment by drom** [comment]
I have the same problem. Any guidance here?

**Comment by CrouseMatthew** [comment]
I'm Seeing this as well. Ubuntu 14.4  Atom 0.190.0 4/7/2015, 2:14:19 PM

**Comment by CrouseMatthew** [comment]
My problem was solved by following this. https://discuss.atom.io/t/how-to-enable-spell-checking-for-another-language/4895

**Comment by opennomad** [comment]
This used to work in 0.192.0. It no longer works. I tried both 0.194.0 and 0.196.0 and neither of them do the right thing for spell check. In the console for 0.196.0 i see:

```
Error starting spell check task Error: channel closed
  at ChildProcess.target.send (child_process.js:396:26)
  at Task.module.exports.Task.send (/usr/share/atom/resources/app.asar/src/task.js:114:27)
  at Task.module.exports.Task.start (/usr/share/atom/resources/app.asar/src/task.js:105:12)
  at SpellCheckTask.module.exports.SpellCheckTask.start (/usr/share/atom/resources/app.asar/node_modules/spell-check/lib/spell-check-task.js:31:66)
  at SpellCheckView.module.exports.SpellCheckView.updateMisspellings (/usr/share/atom/resources/app.asar/node_modules/spell-check/lib/spell-check-view.js:104:26)
  at /usr/share/atom/resources/app.asar/node_modules/spell-check/lib/spell-check-view.js:68:26
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1111:25
```

**Comment by npalmer** [comment]
I'm experiencing this as well, unfortunately. Ubuntu 14.04 Atom 0.194.0 5/10/2015

**Comment by mhozza** [comment]
same issue here Atom 0.196.0/Ubuntu 15.04,
spell-check 0.56.0

**Comment by yourcenar** [comment]
0.192.0 was the last version that worked. 0.193.0 and each subsequent release has a non-functional spell-checker, at least on Linux, and my hunch is the asar change means hunspell can't read the wordlist.

**Comment by THPubs** [comment]
The latest release 199 says it have fixed the issue. But the still it does not work for me! Do we have to enable it separately?

**Comment by kevinsawicki** [comment]
> The latest release 199 says it have fixed the issue. But the still it does not work for me! Do we have to enable it separately?

As long as the package is enabled and you are editing a file that is configured to have spell checking, you should see misspelled words highlighted.

**Comment by THPubs** [comment]
The package is enabled, Tried `html.erb`, `html`, and `md`, none worked!

**Comment by jseto** [comment]
It worked for me without any change. Just upgrading. Try to open a markdown file with md extension and leave grammar settings empty.

**Comment by THPubs** [comment]
@jseto Tried but not working :-( What's your OS? Im on Elementary Freya (Ubuntu 14.04)

**Comment by jseto** [comment]
@THPubs same yours

**Comment by THPubs** [comment]
@jseto Oh... How did you update? Complete re-install? Can it be a conflict with other plugins?
Here are my packages :
    atom-beautify@0.27.1
    autocomplete-ruby@0.1.0
    base16-syntax@1.0.1
    chester-atom-syntax@0.1.1
    color-picker@1.7.0
    dark-flat-ui@1.1.4
    file-icons@1.5.5
    git-blame@0.4.3
    highlight-line@0.10.2
    isotope-ui@2.2.0
    less-than-slash@0.6.0
    linter@0.12.2
    linter-htmlhint@0.0.15
    linter-rubocop@0.2.3
    merge-conflicts@1.3.1
    minimap@4.8.0
    no-caffeine-syntax@0.14.1
    pigments@0.2.1
    predawn-ui@0.3.8
    rails-snippets@1.9.4
    rails-transporter@1.2.0
    ruby-block@0.3.3
    seti-syntax@0.4.0
    seti-ui@0.7.1
    terminal-status@1.6.7

**Comment by THPubs** [comment]
Just discovered, it works in `markdown` but not in files like html,erb

**Comment by lee-dohm** [comment]
@THPubs You can set the grammars that you want the spell check to work in on the Settings View for the Spell Check package.

**Comment by mnquintana** [comment]
> @THPubs You can set the grammars that you want the spell check to work in on the Settings View for the Spell Check package.

Yup! @THPubs spell-check is only configured for Plain Text, Markdown, and Git Commit Messages out of the box. From the spell-check Readme:

> By default spell check is enabled for the following files:
>
> - Plain Text
> - GitHub Markdown
> - Git Commit Message

**Comment by jseto** [comment]
@THPubs http://www.atomtips.com/spellcheck-in-atom/

**Comment by THPubs** [comment]
Oh very sorry for my mistake! I enabled for html and erb but couldn't do it for rb. Any one know how?

    text.html.basic, text.html, text.html.erb,source.rb
