### ISSUE TITLE
Performance: SpellCheck causes large CPU load

### ISSUE THREAD

**Issue by backspaces** [atom/spell-check#58]
I have not been able to get spell checking to work on either my mini or my MBAir (original).  Both latest Yosemite.  Attached Activity Monitor is the usual problem: an Atom Helper and AppleSpell both jump up to large CPU values.

![image](https://cloud.githubusercontent.com/assets/124366/7424946/8900540a-ef65-11e4-84bb-e73cbaffe17f.png)

**Comment by izuzak** [comment]
@backspaces Which version of Atom are you using and which version of OSX? Can you clarify what exactly you mean by "not been able to get spell checking to work" (are you seeing an error, are you not seeing any spell check suggestions, or something else)? Could you provide some steps to reproduce the problem and a link to a file with which you are reproducing this? Does this problem happen for all files or only some files?

**Comment by backspaces** [comment]
Hi izuzak, sorry if unclear.

Main issue is huge CPU usage, bad enough that I have to turn it off, thus "can't use".  The picture of the Activity Monitor shows basically 100% of a cpu used.

Secondarily, I found it a bit hard to see the error underlines but that's not a big deal.

**Comment by izuzak** [comment]
@backspaces Thanks for clarifying, but I'm still unclear on a few things.

Did I understand correctly that the high CPU usage is present only when the spellcheck package is enabled? Can you confirm that you're _not_ seeing this high CPU usage when that package is disabled? You can disable it in Settings. 

Also, does this problem happen for all files or only some files (for example, very large files)?

> Secondarily, I found it a bit hard to see the error underlines but that's not a big deal.

I guess that will depend on the theme you are using. The default styling for those underlines is [here](https://github.com/atom/spell-check/blob/master/styles/spell-check.atom-text-editor.less). You can tweak that in you local [styles.less file](https://atom.io/docs/latest/using-atom-basic-customization#style-tweaks), for example to make the lines thicker:

```less
atom-text-editor::shadow .spell-check-misspelling .region {
  border-bottom: 3px dashed rgba(250, 128, 114, .5);
}
```

Does that help?

**Comment by lee-dohm** [comment]
There is also my [red-wavy-underline package](https://atom.io/packages/red-wavy-underline) that uses the somewhat familiar red wavy underline for spelling errors.

**Comment by backspaces** [comment]
It seems that spell-check only spiked cpu usage when first enabled, it eventually settled.

I did remove an ancient subfolder that *did* have large files, dictionaries for older command line tools. One of these was 2.0M. 

So either patience (startup high cpu use) or removing the old, unused dictionary files solved the problem.

Currently spell-check is working well, yay! Thanks for the help!

**Comment by 50Wliu** [comment]
Glad to hear it! :smile:

**Comment by paulklemm** [comment]
I still experience this issue. For large LaTeX files (> 2k lines), the processes `Applespell` and `Atom Helper` spike in CPU usage. I've tried a fresh install of Atom (deleting the Atom home folder), but the problem persists.

My guess is that Atom requires Applespell to check the whole document instead of the current input every time new input is registered. The problem also does *not* settle after editing the file for a while.

I'm on Atom 1.1.0 with OSX 10.11.1 (15B42).
<img width="787" alt="screen-shot-2015-11-05-14-07-34-epjmu7w0xw-1" src="https://cloud.githubusercontent.com/assets/2169489/10969278/87679bca-83c7-11e5-91e5-eb61b5881138.png">

**Comment by ssfrr** [comment]
I'm seeing this as well. Massive CPU usage, even though my .tex file is only about 850 lines long. It also seems to be a problem if I make many edits, as if it's queuing up a bunch of spellchecks instead of interrupting the previous one.

**Comment by rnicholus** [comment]
I had this issue as well, but it [seems to be fixed in Atom 1.5.0](https://github.com/atom/atom/issues/10306#issuecomment-170745928). I'm running beta1 and the moment.

**Comment by X-Ryl669** [comment]
Same for me with 1.7.0-beta4 (and previous). The file being edited is huge (> 5k lines) and the Atom Helper & Applespell are consuming a complete CPU core if Spellcheck is enabled.

**Comment by ChrisChinchilla** [comment]
@50Wliu 

This is still happening with Atom 1.21 (26-32% CPU) and I have the `spell-check` package disabled as I use linter spell with aspell, so at least if the package is disabled, then surely there should be no CPU usage? Sometimes AppleSpell is spiking CPU if I don't even have documents open.

This has got worse recently, not sure if it's recent changes to Atom or High Sierra. How can I help debug this?

**Comment by RobertCordes** [comment]
This is still happening for me. Atom Helper was using a good chunk of the CPU. After disabling the spell-check package everything is running smoothly.

**Comment by MarkKelly-DTU** [comment]
Just after the most recent update (the last couple weeks for me) to El Capitan, I now for the first time have AppleSpell also taking >99% of CPU, causing lots of heat and fan usage.  
It seems to be worst when I use Mathematica (11.3) and have lots of graphics therein.

**Comment by rsese** [comment]
Since the original issue was closed, can someone open a new issue and fill out the issue template so we can track it?
