### ISSUE TITLE
[electron-v0.29.2] spellchecker throws Uncaught Error: Module version mismatch. Expected 44, got 43.

### ISSUE THREAD

**Issue by kamesh-a** [atom/spell-check#71]
I have recompiled the https://github.com/atom/node-spellchecker 
tried all ways which was specified in https://github.com/atom/electron/blob/master/docs/tutorial/using-native-node-modules.md

Interesting thing is i compiled both midi and spellchecker. midi works spellchecker fails. Can anybody let us know whether its working in your end. we are doing something wrong.

"Spellchecker" is essential for many application.

Tried switching to iojs 2.3.3 included process.versions which i tried to compile with.
```
{ http_parser: '2.5.0',
  node: '2.3.3',
  v8: '4.2.77.20',
  uv: '1.6.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  modules: '44',
  openssl: '1.0.2c' }
```
via:
```
export npm_config_disturl=https://atom.io/download/atom-shell
export npm_config_target=0.29.2
export npm_config_arch=x64
HOME=~/.electron-gyp npm install spellchecker

```

<img width="1438" alt="spellchecker_critical_need" src="https://cloud.githubusercontent.com/assets/3531949/8549720/f12cc306-24e9-11e5-875e-37fd57ecf9a0.png">

**Comment by maxbrunsfeld** [comment]
It looks like `spellchecker` was compiled against an earlier version of Electron (the `NODE_MODULE_VERSION` is 43). You should just need to recompile it to work with Electron 0.29.2. The easiest way is with `electron-rebuild`.

**Comment by kamesh-a** [comment]
Thanks found the issue, there was global module, wil previous compilation that was being referenced of the local one.
