### ISSUE TITLE
Increase thickness of red underline

### ISSUE THREAD

**Issue by orschiro** [atom/spell-check#86]
Dear all, 

Would it be possible to slightly increase the thickness of the red underline? 

On white/light themes, mispelled words are very difficult to recognise:

![image](https://cloud.githubusercontent.com/assets/170947/10121525/3915d702-64f0-11e5-80c3-38030e207338.png)

Thankfully,

Robert

**Comment by izuzak** [comment]
@orschiro You can increase the thickness yourself -- that's the neat thing about Atom, you can change and style just about anything.

Open your styles.less file (Atom > Open your stylesheet menu) and then put this there:

```
atom-text-editor::shadow .spell-check-misspelling .region {
  border-bottom: 3px dashed red;
}
```

You should now see thicker underlines:

<img width="498" alt="screen shot 2015-09-27 at 10 22 33" src="https://cloud.githubusercontent.com/assets/38924/10121874/e39489e2-6501-11e5-8d94-0df1bf90d9c2.png">

That's probably a bit too thick, so feel free to experiment with the thickness and color.

Still, I do think that it would be useful if the line was a bit clearer by default in One Light. Wondering if @simurai has any thoughts.

**Comment by orschiro** [comment]
@izuzak 

This looks much better, thank you! I will modify the style but would love to see this being the default for One Light, too.

**Comment by simurai** [comment]
Or with a `background-color` instead:

![screen shot 2015-09-29 at 10 56 56 am](https://cloud.githubusercontent.com/assets/378023/10155749/e730640a-66b3-11e5-8d71-fb6359a8ad56.png)

```css
atom-text-editor::shadow .spell-check-misspelling .region {
  border-bottom: none;
  background-color: hsla(0, 100%, 64%, 0.4);
}
```

Looks more like a marker, but for most probably too strong. :smirk:

As for the default, I made a PR #87 that makes the border easier to spot.

**Comment by orschiro** [comment]
@simurai 

I like the marker style. Thank you! ツ
