### ISSUE TITLE
Spell check underscored_words

### ISSUE THREAD

**Issue by craig-landry** [atom/spell-check#93]
Of the following, spell check correctly identifies the 1st as valid, the 2nd as misspelled, but the 3rd is incorrectly identified (or perhaps ignored) as being valid.  Please add ability to tokenize on underscores (important to Ruby developers) to handle cases like the 3rd below:

1. birthday = true
2. birthdaay = true
3. birthdaay_cards = true

**Comment by 50Wliu** [comment]
Closing in favor of #91, #73, and #34.
