### ISSUE TITLE
Spell checking is not working for Go files

### ISSUE THREAD

**Issue by cristian-sima** [atom/spell-check#94]

**Comment by izuzak** [comment]
Hey @cristian-sima :wave:. As mentioned in [the README](https://github.com/atom/spell-check#spell-check-package-), "by default spell check is enabled for the following files: Plain Text, GitHub Markdown, Git Commit Message, and AsciiDoc". You can enable it for more languages using the instructions in the README.

**Comment by cristian-sima** [comment]
Hi izuzak.

Thank you for your response. I followed the instructions, but I have another problem

For go codel, the syntax appear to be wrong


![asdasdsa](https://cloud.githubusercontent.com/assets/12199042/10870236/a21f79ea-80bd-11e5-9c33-8dd5da0d6bf1.PNG)

Is any possibility to check just the comments ?

Thank you

**Comment by izuzak** [comment]
> Is any possibility to check just the comments ?

No, that's not possible currently. There's already an open issue which tracks this feature request: https://github.com/atom/spell-check/issues/2, so I suggest you subscribe to that for updates.

**Comment by cristian-sima** [comment]
Thanks
