### ISSUE TITLE
Create "add to dictionary" option for spell-checker

### ISSUE THREAD

**Issue by fusion809** [atom/spell-check#95]
Hi,

It is inevitable that some people will want to use words that are not in the dictionary used by the spell-checker package and hence I propose an option like "Add to dictionary" be added to the context-menu additions of this package.

Thanks for your time,
Brenton

**Comment by izuzak** [comment]
Hey @fusion809 -- that's a great idea. I believe we're already tracking that feature request over in https://github.com/atom/spell-check/issues/10 so I'm going to close this in favor of that. Also, I'll tweak the title of the issue a bit since it seems it's not really discoverable.
