### ISSUE TITLE
False spelling error on I've

### ISSUE THREAD

**Issue by bobrocke** [atom/spell-check#99]
Improper flag of a non-error:

![2015-11-21 at 4 29 pm](https://cloud.githubusercontent.com/assets/2962426/11320632/31ed71c6-906d-11e5-8431-7dd5f0ea15c0.jpg)

**Comment by anderoonies** [comment]
This looks like it's an issue specifically with `}I've`, not with `I've`.
The [`wordRegex`](https://github.com/atom/spell-check/blob/master/lib/spell-check-handler.coffee#L3) doesn't see the start of the word until the apostrophe because it's only looking for square brackets, not curly braces.
